---
title: "Työperäinen muutto"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "fig_tyomuutto/",
  fig.height=3, fig.width=5.3, dpi=300, out.width = "650px"
)

devtools::load_all()

library(RColorBrewer)
library(glue)
library(ggptt)

set_ptt(10, base_family = "sans")
theme_update(plot.subtitle = element_text(colour = "grey50", size = 9), 
             plot.margin = margin(0.5, 0.5, 3, 0.5))


atyyppi_colour <- c(brewer.pal(6, "Oranges")[6:4], brewer.pal(6, "Blues")[6:5] , brewer.pal(6, "Greens")[6:5])

```

```{r data}

data("tyo_muutto_atyyppi", "tyo_muutto_ku", "dat_muutto_aikasarja_km")

```

# Pendelöivien osuus kunnassa työssäkäyvistä

```{r pend_atyyppi}

time_range <- range(tyo_muutto_atyyppi$time)

tyo_muutto_atyyppi %>% 
  select(time, aluetyyppi, 'Työperäinen' = tyo_muutto_netto, '18-80-vuotiaat' = tmuutto_netto) %>% 
  mutate(aluetyyppi = fct_recode(aluetyyppi, 
                                 'Muu maaseutu' = "Ydinmaaseutu",
                                 'Muu maaseutu' = "Harvaan asuttu maaseutu"),
         aluetyyppi = ggptt::line_wrap(aluetyyppi, 25)) %>% 
  group_by(time, aluetyyppi) %>% 
  summarise_all(sum) %>% 
  ungroup() %>% 
  gather(vars, values, -time, -aluetyyppi) %>% 
  ggplot(aes(time, values, colour = vars)) +
  facet_wrap( ~ aluetyyppi) +
  geom_line() +
  geom_h0() +
  # scale_colour_manual(values = atyyppi_colour) +
  the_title_blank(c("x", "l")) +
  labs(subtitle = glue("Samana vuonna asuin- ja työpaikan kuntaan vaihtaneiden ja 18-80-vuotiaiden nettomuutto vuosina {time_range[1]}-{time_range[2]}."),
       title = "Työperäinen nettomuutto",
       caption = "Lähde: PTT, Tilastokeskus",
       y = "henkeä")

# ggsave("tyo_muutto_atyyppi.png", height = 6, width = 12)  

```

```{r pend_atyyppi_maara}

dat_tulopendelointi_tyyppi %>% 
  filter(koulutusaste == "Yhteensä",
         ika == "Yhteensä") %>% 
  mutate(pendelointi = fct_recode(pendelointi, 
                                  kaikki = "Yhteensä",
                                  asuinkunnassa = "Asuinkunnassaan työssäkäyvät",
                                  pendeloivat = "Alueelle pendelöivät")) %>% 
  spread(pendelointi, values) %>% 
  mutate(values = pendeloivat) %>% 
  ggplot(aes(time, values, colour = aluetyyppi)) +
  geom_line()
  

```


# Muutto muodot

```{r muutto_km}

dat_muutto_aikasarja_km %>% 
  filter(grepl("seutukuntien", tiedot)) %>% 
  ggplot(aes(time, value, colour = tiedot)) +
  geom_line()

```

```{r muutto_km2}

pdat_sk_muutto <- dat_muutto_aikasarja_km %>% 
  filter(tiedot %in% c("seutukuntien_valinen_muutto", 
                       "seutukuntien_valinen_tyoikaisten_muutto",
                       "seutukuntien_valinen_tyon_siirtyminen",
                       "seutukuntien_valinen_tyota_siirtava_muutto",
                       "seutukuntien_valinen_tyollisten_muutto",
                       "seutukuntien_valinen_tyottomien_tyollistava_muutto",
                       "seutukuntien_valinen_tyovoiman_ulkopuolelta_tyollistava_muutto")) %>% 
  mutate(tiedot = gsub("seutukuntien_valinen_", "", tiedot),
         tiedot = gsub("tyollistava", "työllistävä", tiedot),
         tiedot = gsub("siirtava", "siirtävä", tiedot),
         tiedot = gsub("tyoikaisten", "työikaisten", tiedot),
         tiedot = gsub("tyo", "työ", tiedot),
         tiedot = gsub("_", " ", tiedot),
         tiedot = fct_reorder(tiedot, -value, mean)) %>% 
  mutate(value = as.integer(value)) 

pdat_sk_muutto %>% 
  ggplot(aes(time, value/1000, colour = tiedot)) +
  geom_line() +
  scale_x_continuous(breaks = scales::pretty_breaks()) +
  labs(title = "Seutukuntien välinen muutto ja työpaikan siirtyminen",
       y = "1000 henkeä", x = NULL,
       caption = "Lähde: Tilastokeskus, PTT") +
  theme(legend.text = element_text(size = 10))



```

```{r muutto_km2_table}

pdat_sk_muutto %>% 
  filter(time == max(time)) %>% 
  knitr::kable()

```


  
```{r kuntien_valinen}
dat_muutto_aikasarja_km %>% 
  filter(tiedot %in% c("kuntien_valinen_muutto", 
                       "kuntien_valinen_tyoikaisten_muutto",
                       "kuntien_valinen_tyon_siirtyminen",
                       "kuntien_valinen_tyota_siirtava_muutto",
                       "kuntien_valinen_tyollisten_muutto",
                       "kuntien_valinen_tyottomien_tyollistava_muutto")) %>% 
  ggplot(aes(time, value, colour = tiedot)) +
  geom_line()
```
  
```{r maakuntien_valinen}

dat_muutto_aikasarja_km %>% 
  filter(tiedot %in% c("maakuntien_valinen_muutto", 
                       "maakuntien_valinen_tyoikaisten_muutto",
                       "maakuntien_valinen_tyon_siirtyminen",
                       "maakuntien_valinen_tyota_siirtava_muutto",
                       "maakuntien_valinen_tyollisten_muutto",
                       "maakuntien_valinen_tyottomien_tyollistava_muutto")) %>% 
  ggplot(aes(time, value, colour = tiedot)) +
  geom_line()

```  
  
  
  
