---
title: "Muuttoliike"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyr)
library(ggplot2)
library(ggptt)

devtools::load_all()
set_gg(theme_ptt(), "ptt")

```
Muuttojen absoluuttinen määrä Suomessa 1990 - 2017

```{r}

data(dat_kokonaismuutto)

ggplot(dat_kokonaismuutto, aes(x = vuosi, y = muuttoja, col = muuton_tyyppi)) +
  geom_line() +
  theme(legend.title = element_blank()) +
  ylab("Muuttoja") +
  xlab(NULL) +
  theme(legend.position = "bottom", legend.justification = "left") +
  scale_y_continuous(labels = deci_comma,
                     breaks = scales::pretty_breaks(n = 6)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  scale_color_discrete(labels = c("Maakuntien väliset muutot",
                                  "Seutukuntien väliset muutot",
                                  "Kuntien väliset muutot",
                                  "Kuntien sisäiset muutot")) +
  theme(legend.text = element_text(size = 8))

```
Muuttojen määrä suhteessa väkilukuun Suomessa 1990 - 2017

```{r}

ggplot(dat_kokonaismuutto, aes(x = vuosi, y = muuttoaste, col = muuton_tyyppi)) +
  geom_line() +
  theme(legend.title = element_blank()) +
  ylab("Muuttoaste") + 
  xlab(NULL) +
  theme(legend.position = "bottom", legend.justification = "left") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  scale_color_discrete(labels = c("Maakuntien väliset muutot",
                                  "Seutukuntien väliset muutot",
                                  "Kuntien väliset muutot",
                                  "Kuntien sisäiset muutot")) +
  theme(legend.text = element_text(size = 8))

```
Nettomuuttokertymät seutukunnittain. Kunkin seutukunnan vuosittaisten nettomuuttojen summa vuosilta 1990-2017

```{r}

# Hae data
  data(dat_muuttotiedot_kunnittain)
  nettomuutto_data <- filter(dat_muuttotiedot_kunnittain, Tiedot == "nettomuutto")

nettomuutto_data %>% group_by(seutukunta) %>%
  summarize(nettomuutto = sum(values)) %>%
  ggplot(aes(x = reorder(seutukunta, nettomuutto), y = nettomuutto)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab(NULL) +
  ylab("Nettomuutto") +
  scale_y_continuous(limits = c(-50000, 140000), labels = deci_comma)
```
