---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(tidyverse)
library(ggplot2)
library(ggptt)

devtools::load_all()
set_gg(theme_ptt(), "ptt")
```

Pendelöijien absoluuttinen määrä koko maassa. Huom. koko maan summia laskettaessa ei ole väliä summaileekko kohde- vai lähtöalueiden pendelöintejä. 

```{r, echo = FALSE}

data(dat_pendelointi)

dat_pendelointi %>% group_by(vuosi) %>%
  summarize(commuters = sum(lahtopendelointi)) %>%
  ggplot(aes(y = commuters, x = vuosi)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  geom_line() +
  #ggtitle("Pendelöijien määrä Suomessa 1987 - 2015") + #Kuntien välinen pendelöinti
  ylab("Pendelöijien määrä") +
  xlab(NULL) +
  scale_y_continuous(limits = c(400000,800000), labels = deci_comma)
```

Pendelöijien osuus työllisistä koko maassa

```{r, echo = FALSE}

dat_pendelointi %>% group_by(vuosi) %>%
  summarize(pendeloijat_yhteensa = sum(lahtopendelointi),
            ei_pendeloijat_yhteensa = sum(asuinkunnassaan_tyossakayvat)) %>%
  mutate(pendelointiosuus = pendeloijat_yhteensa /
           (pendeloijat_yhteensa + ei_pendeloijat_yhteensa)) %>%
  ggplot(aes(y = pendelointiosuus, x = vuosi)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  geom_line() +
  #ggtitle("Pendelöijien osuus työllisistä Suomessa 1987 - 2015") +
  ylab("Pendelöijien osuus työllisistä") +
  xlab(NULL) +
  scale_y_continuous(limits = c(0.19,0.35), labels = percent_comma)
```

Pendelöinti kunnittain

```{r}
pendelointi_kunnittain <- dat_pendelointi %>% 
                          group_by(alue) %>%
                          summarize(asuinkunnassaan_tyossakayvat = sum(asuinkunnassaan_tyossakayvat),
                                    tulopendelointi = sum(tulopendelointi),
                                    lahtopendelointi = sum(lahtopendelointi))
                         
```

