---
title: "Raportin kuviot"
author: "Janne Huovari"
date: "14 10 2019"
output: html_document
---

```{r setup, include=FALSE}


library(tidyverse)
library(ggplot2)
library(ggptt)
library(gridExtra)
library(RColorBrewer)
library(ggpubr)
library(here)

devtools::load_all()
set_proj()
knitr::opts_chunk$set(fig.path = "Raportin_kuviot/")

data(dat_kokonaismuutto)

muutto_ptoim1_dat <- readRDS(here("data/paa-asiallinen_toiminta_ja_muutto/muuttoaikasarjat_kokomaa_ptoim1_ulos.rds"))
  
```


# Muuttojen absoluuttinen määrä

```{r muutot90_17}

p1 <- dat_kokonaismuutto %>%
  ggplot(aes(x = vuosi, y = muuttoja, col = muuton_tyyppi)) +
  geom_line() +
  theme(legend.title = element_blank()) +
  ylab("Muuttoja") +
  xlab(NULL) +
  #ggtitle("Muuttojen määrä Suomessa 1990 - 2016") +
  geom_hline(yintercept = 0,
             color = "black",
             linetype = 2) +
  theme(legend.position = "bottom", legend.justification = "left") +
  scale_y_continuous(labels = deci_comma,
                     breaks = scales::pretty_breaks(n = 6)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  scale_color_manual(
    labels = c(
      "Maakuntien väliset muutot",
      "Seutukuntien väliset muutot",
      "Kuntien väliset muutot",
      "Kuntien sisäiset muutot"
    ),
    values = brewer.pal(5, "Blues")[2:5]
  ) +
  guides(colour = guide_legend(nrow = 2))
    
 p1
 
  # ggsave(here("analyysit/Raportin_kuviot/muutot90_17.png"), p1, width = 6.5, height = 5.5)
  
```

# muuttojen suhteellinen määrä (muuttojen absoluuttinen määrä jaettuna väkiluvulla)

```{r muuttoasteet90_17}

 p2 <- dat_kokonaismuutto %>%
   ggplot(aes(x = vuosi, y = muuttoaste, col = muuton_tyyppi)) +
    geom_line() +
    theme(legend.title = element_blank()) +
    ylab("Muuttoaste") + # Muuttojen määrä suhteessa väkilukuun
    xlab(NULL) +
    #ggtitle("Muuttoasteet Suomessa 1990 - 2016") +
    geom_hline(yintercept = 0, color = "black", linetype = 2) +
    theme(legend.position = "bottom", legend.justification = "left") +
    scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
    scale_y_continuous(labels = percent_comma) +
    scale_color_manual(labels = c("Maakuntien väliset muutot",
                                    "Seutukuntien väliset muutot",
                                    "Kuntien väliset muutot",
                                    "Kuntien sisäiset muutot"),
                       values = brewer.pal(5, "Blues")[2:5]) +
  guides(colour = guide_legend(nrow = 2))

 # ggsave("analyysit/Raportin_kuviot/muuttoasteet90_17.png", p2)

 p2
 
```

# Kuvaajat rinnakkain
 
```{r muutot_muuttoasteet90_17, fig.width=10}
p3 <- ggarrange(p1 + guides(colour = guide_legend(nrow = 1)), 
                p2 + guides(colour = guide_legend(nrow = 1)), 
                ncol = 2, common.legend = TRUE, legend = "bottom") 

# ggsave("analyysit/Raportin_kuviot/muutot_muuttoasteet90_17t.png", p3,
#         width = 300,
#         height = 150,
#         units = "mm")

p3 
```

# Muutot toiminnan mukaan

```{r muutot_ptoim1}


ptoim1_tiedot <- c(
    "Työttömät" = "seutukuntien_valinen_tyottomien_muutto",
    "Työlliset" = "seutukuntien_valinen_tyollisten_muutto",
    "Opiskelijat" = "seutukuntien_valinen_opiskelijoiden_muutto",
    "0-14 -vuotiaat" = "seutukuntien_valinen_lasten_muutto",
    "Muut työvoiman ulkopuolella olevat" = "seutukuntien_valinen_palvelusmiesten_muutto",
    "Eläkeläiset" = "seutukuntien_valinen_elakelaisten_muutto",
    "Muut työvoiman ulkopuolella olevat" = "seutukuntien_valinen_muutyovoimanulkopuolella_muutto"
  )

# Seutukuntien väliset muutot


muutto_ptoim1_pdat <- muutto_ptoim1_dat %>% 
  filter(tiedot %in% ptoim1_tiedot) %>%
  mutate(tiedot = fct_recode(tiedot, !!!ptoim1_tiedot)) %>% 
  group_by(tiedot, vuosi) %>% 
  summarise(value = sum(value)) %>% 
  ungroup() 


muutto_ptoim1_pdat %>% 
  ggplot(aes(x = vuosi, y = value)) +
  geom_area(aes(fill = tiedot)) +
  theme_light(14) +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.justification = "left"
  ) +
  scale_fill_manual(values = brewer.pal(8, "Blues")) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 6)) +
  scale_y_continuous(labels = deci_comma) +
  labs(x = NULL, y = "Seutukuntien välisiä muuttoja") +
  stat_summary(fun.y = "sum", geom = "line", color = "black", linetype = 1, size = 1, show.legend = FALSE)


```

```{r muutoto_ptoim1_table}

muutto_ptoim1_pdat %>% 
  filter(vuosi == max(vuosi)) %>% 
  mutate(osuus = 100 * value / sum(value)) %>% 
  knitr::kable(digits = 0)

```

